version: "3"

services:
  api:
    restart: always
    build: ./
    image: fastapi
    ports:
      - "9000:9000"
    networks:
      - main
    volumes:
      - ./app:/usr/src/app/
    env_file: .env
    environment:
      - DEBUG=true
    command: ["run"]

networks:
  main:


